folder_structure:
  alternative_patterns:
  - pattern: (.+)-([0-9]+)
  - pattern: (.+)\s+([0-9]+)
  - pattern: ([^_]+)_
  - pattern: (.+)_([0-9]+)_x_web
  - pattern: (.+)_([0-9]+)
  known_magazines:
  - aliases:
    - orizzonti
    - orz
    - or
    - orizz
    - eni magazine
    - enimagazine
    name: Orizzonti
  - aliases:
    - we
    - w&e
    - we_eni
    - we-eni
    name: WE
  log_level: INFO
  log_unknown: true
  magazine_pattern: (.+)_([0-9]+)
openai:
  api_key: ''
  model: gpt-4o-mini
  temperature: 0.3
  max_tokens: 1000
prompts:
  extract_fields: |
    You are an expert data analyst specializing in content analysis for the energy industry.
    Your task is to analyze the following article from one of ENI's magazines (which are either "Orizzonti" or "WE") and extract specific structured information.

    IMPORTANT FILE INFORMATION:
    File Path: {file_path}

    IMPORTANT RULES:
    1. **Magazine**: The magazine name MUST be either "Orizzonti" or "WE" (case sensitive). These are the ONLY two magazines published by ENI.
    
    2. **Magazine Number**: The issue number should be extracted from either:
       a) The article text itself, if mentioned
       b) The file path, where it's often included in patterns like:
          - Orizzonti_62_x_web (here "62" is the issue number)
          - WE_60 (here "60" is the issue number)
          - We 54 (here "54" is the issue number)
       If you can't find the issue number in either the article or file path, only then return "Not Specified".
       
    3. **Author**: The author's name as mentioned in the article. Use proper capitalization.
    4. **Title**: The article title extracted from the content. Use proper title case.
    5. **Abstract**: Provide a concise summary (1-2 sentences) that captures the key insights. The summary should be in sentence case.
    6. **Theme**: Select the most appropriate primary theme from the following list (return exactly one, using the list's formatting):
       - Energy Transition
       - Sustainability
       - Innovation & Technology
       - Business & Markets
       - Climate & Environment
       - Geopolitics
       - Corporate News
       - Industry Insights
       - Social Impact
       - Culture & Society

    7. **Format**: Identify the content format from these options:
       - Article
       - Interview
       - Report
       - Case Study
       - Analysis
       - Commentary
       - Photo Gallery
       - Infographic
       - News Brief

    8. **Geographic Area**: Identify the specific geographic region(s) discussed in the article. Use standardized names (e.g., "Northern Italy", "Gulf of Mexico", "Southeast Asia") and return "Not Specified" if absent.
    9. **Keywords**: Provide 3-5 relevant keywords describing the article, in lowercase and separated by commas.

    Ensure that your response is strictly in JSON format, with no extra text. The JSON must include these fields: magazine, magazine_no, author, title, abstract, theme, format, geographic_area, keywords.

    Article text: {text_content}
  reconcile_metadata: |
    You are an expert data validator for ENI Magazine, tasked with reconciling metadata extracted from folder structures and document content.

    You have been provided with:
    1. The file path: "{file_path}"
    2. Preliminary metadata extracted from the folder structure:
       - Magazine: "{magazine}"
       - Magazine Number: "{magazine_no}"
       - Author: "{author}"
       - Title: "{title}"
    3. The complete article text content

    **IMPORTANT**: Verify the metadata against the article content with special attention to:

    1. **Magazine**: Must be either "Orizzonti" or "WE" (case sensitive). The folder suggests "{magazine}" but you should verify this from the content. ENI only publishes these two magazines, so any other magazine name is incorrect.

    2. **Magazine Number**: Should be a numeric issue number. The folder suggests "{magazine_no}" but you should verify if the article mentions a different issue number.

    3. **Author**: Verify if the author name from the folder ("{author}") matches the author mentioned in the article content. Use proper capitalization.

    4. **Title**: Determine the correct article title from the content. Use proper title case.

    5. **Abstract**: Provide a concise summary (1-2 sentences) that captures the key insights. The summary should be in sentence case.

    6. **Theme**: Select the most appropriate primary theme from the following list (return exactly one, using the list's formatting):
       - Energy Transition
       - Sustainability
       - Innovation & Technology
       - Business & Markets
       - Climate & Environment
       - Geopolitics
       - Corporate News
       - Industry Insights
       - Social Impact
       - Culture & Society

    7. **Format**: Identify the content format from these options:
       - Article
       - Interview
       - Report
       - Case Study
       - Analysis
       - Commentary
       - Photo Gallery
       - Infographic
       - News Brief

    8. **Geographic Area**: Identify the specific geographic region(s) discussed in the article. Use standardized names (e.g., "Northern Italy", "Gulf of Mexico", "Southeast Asia") and return "Not Specified" if absent.

    9. **Keywords**: Provide 3-5 relevant keywords describing the article, in lowercase and separated by commas.

    Your response must be in strict JSON format with the following structure:
    {
      "magazine": "verified magazine name (must be 'Orizzonti' or 'WE')",
      "magazine_no": "verified magazine issue number",
      "author": "verified author name",
      "title": "verified article title",
      "abstract": "concise summary in sentence case",
      "theme": "one of the listed themes, exactly as provided",
      "format": "one of the provided formats",
      "geographic_area": "standardized region or 'Not Specified'",
      "keywords": "comma-separated list of keywords in lowercase"
    }

    Example Output:
    {
      "magazine": "Orizzonti",
      "magazine_no": "62",
      "author": "John Smith",
      "title": "Renewable Energy Solutions for Tomorrow",
      "abstract": "This article explores innovative renewable energy technologies being developed for future implementation.",
      "theme": "Energy Transition",
      "format": "Article",
      "geographic_area": "Global",
      "keywords": "renewable energy, innovation, sustainability, future technologies, climate solutions"
    }

    Article text content:
    {text_content}
